[template]

# The name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/conf.d/templates` for these files by default
src = "nginx.tmpl"

# The location to place the rendered configuration file
#Original: dest = "/etc/nginx/sites-enabled/app.conf"
#Modified destination below:
dest = "/etc/nginx/nginx.conf"

# The etcd keys or directory to watch.  This is where the information to fill in
# the template will come from. (originally for apache)
# keys = [ "/services/apache" ]
keys = [ "/services/todo"]

# File ownership and mode information
owner = "root"
mode = "0644"

# These are the commands that will be used to check whether the rendered config is
# valid and to reload the actual service once the new config is in place
# Modified to work with the confd module
check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
reload_cmd = "/usr/sbin/service nginx reload"
